on:
  workflow_call:
    inputs:
      tox:
        type: string
        description: What to run under tox
        required: true


jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Run tox
        run: tox -e ${{ inputs.tox }}
