on:
  workflow_call:
    inputs:
      tox:
        type: string
        description: What to run under tox
        required: true


jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Run tox
        run: tox -e ${{ inputs.tox }}
